config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  get 'home/search'

  get 'documents/user/:id' => 'documents#user'

  get 'documents/test'

  resources :documents

  devise_for :users

  root 'home#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
  before_validation :file2md5

  validates :md5, uniqueness: {message: "El archivo ya existe"}
  validates :title, :abstract, :file, presence: true
  validates :abstract, length: {maximum: 120}

  mount_uploader :file, FileUploader

  belongs_to :user

  protected
    def file2md5
      self.md5 = Digest::MD5.hexdigest(File.read(self.file.path))
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
require 'Winnower'
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:user]

  respond_to :html

  def index
    @documents = Document.all
    respond_with(@documents)
  end

  def show
    respond_with(@document)
  end

  def user
    @user = User.find(params[:id])
    respond_with(@user)
  end

  def new
    @document = Document.new
    respond_with(@document)
  end

  def edit
  end

  def create
    @document = Document.new(document_params)
    @document.save
    respond_with(@document)
  end

  def update
    @document.update(document_params)
    respond_with(@document)
  end

  def destroy
    @document.destroy
    respond_with(@document)
  end

  def test
    redirect_to new_user_session_path if current_user.admin
    path = Rails.root.join("public", "uploads","document","file")
    @win = Winnower.new(15,10,path)
    @win.execute
  end

  private
    def set_document
      @document = Document.find(params[:id])
    end

    def document_params
      params[:document][:user_id] = current_user.id
      params.require(:document).permit(:title, :file, :md5, :user_id, :public, :abstract)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end

  def search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def date_format(date)
    if date
      date.strftime("%d/%m/%Y")
    else
      "- -"
    end
  end

  def date_time_format(date)
    if date
      date.strftime("%d/%m/%Y - %l:%M %p")
    else
      "- -"
    end
  end

end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/documents/_form.html.erb
<%= form_for @document, :html => { class: "form-horizontal document" } do |f| %>

    <% if @document.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @document.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <%= error_span(@document[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :file, class: 'control-label' %>
    <div class="controls">
      <%= f.file_field :file, class: 'form-control' %>
    </div>
    <%= error_span(@document[:md5]) %>
  </div>
  <div class="control-group">
    <%= f.label :abstract, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :abstract, class: 'form-control' %>
    </div>
    <%= error_span(@document[:abstract]) %>
  </div>
  <!-- <div class="control-group">
    <%= f.label :md5, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :md5, class: 'form-control' %>
    </div>
    <%= error_span(@document[:md5]) %>
  </div> -->
  <div class="control-group">
    <%= f.label :public, class: 'control-label' %>
    <div class="controls">
      <%= f.check_box :public%>
    </div>
    <%= error_span(@document[:public]) %>
  </div>


  <%= f.submit nil, class: 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            documents_path, class: 'btn btn-default' %>

<% end %>

app/views/documents/edit.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/documents/index.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:file) %></th>
      <th><%= model_class.human_attribute_name(:md5) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:public) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= link_to document.id, document_path(document) %></td>
        <td><%= link_to document.title, document.file.url %></td>
        <td><%= document.file %></td>
        <td><%= document.md5 %></td>
        <td><%= document.user_id %></td>
        <td><%= document.public %></td>
        <td><%= date_time_format document.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_document_path(document), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      document_path(document),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_document_path,
            :class => 'btn btn-primary' %>

app/views/documents/new.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/documents/show.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @document.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:file) %>:</strong></dt>
  <dd><%= @document.file %></dd>
  <dt><strong><%= model_class.human_attribute_name(:md5) %>:</strong></dt>
  <dd><%= @document.hash %></dd>
  <dt><strong><%= model_class.human_attribute_name(:public) %>:</strong></dt>
  <dd><%= @document.public %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              documents_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_document_path(@document), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              document_path(@document),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/documents/test.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Archivo 1</th>
      <th>Archivo 2</th>
      <th>Porcentaje de similitud</th>
    </tr>
  </thead>
  <tbody>
    <% @win.averages.sort_by(&:last).reverse.each_with_index do |key,index|%>
    <% k1,k2 = key[0].split("-")  %>
    <tr>
      <td><%= k1 %></td>
      <td><%= k2 %></td>
      <td><%= "#{(key[1]*1).to_i}%" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/documents/user.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:abstract) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @user.documents.each do |document| %>
      <tr>
        <td><%= document.title %></td>
        <td><%= document.abstract %></td>
        <td><%= date_format document.created_at %></td>
        <td><%= date_format document.updated_at %></td>
        <td><%= link_to '', document.file.url, class: "btn btn-primary fa fa-eye" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Facultad</th>
      <th>Nombre</th>
      <th>Resumen</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>UANL</td>
      <td><%= link_to user.email, "/documents/user/#{user.id}" %></td>
      <td>BIOGRAFIA CHIDA</td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/home/search.html.erb
<h1>Home#search</h1>
<p>Find me in app/views/home/search.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "IAdmin" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">IAdmin</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">

            <% if current_user %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown">Admin <span class="fa fa-user"> </span><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to :Crear, new_user_registration_path %></li>
              </ul>
            </li>
            <% end %>

            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
            <li>
              <%= link_to " Salir", destroy_user_session_path,
                method: :delete, class: "fa fa-upload" %>
            </li>
            <% else %>
            <li>
              <%= link_to " Entrar", new_user_session_path, class: "fa fa-user" %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Tweets</h3>
            <ul class="nav nav-list">
              <li class="nav-header">@FIME_Oficial</li>
              <li>@FIME_Oficial encuentro ITS en el edificio 4 este 19 de Noviembre</li>
              <li>@FIME_Oficial encuentro ITS en el edificio 4 este 19 de Noviembre</li>
              <li>@FIME_Oficial encuentro ITS en el edificio 4 este 19 de Noviembre</li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>